In [64]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#import dataset
fraud = pd.read_csv(r"C:\Users\neetac1973\Downloads\Fraud_check (1).csv")
fraud

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

In [8]:
##Converting Work Experience variable to bucketing. 
fraud["experience"]="<=30000"
fraud.loc[fraud["Work.Experience"]>=30,"experience"]="More experienced"
fraud.loc[fraud["Work.Experience"]<=30,"experienc"]="Good"
fraud

Undergrad Marital.Status  City.Population  Work.Experience Urban   income  \
0          NO         Single            50047               10   YES  <=30000   
1         YES       Divorced           134075               18   YES  <=30000   
2          NO        Married           160205               30   YES  <=30000   
3         YES         Single           193264               15   YES  <=30000   
4          NO        Married            27533               28    NO  <=30000   
..        ...            ...              ...              ...   ...      ...   
595       YES       Divorced            39492                7   YES  <=30000   
596       YES       Divorced            55369                2   YES  <=30000   
597        NO       Divorced           154058                0   YES  <=30000   
598       YES        Married           180083               17    NO  <=30000   
599        NO       Divorced           158137               16    NO  <=30000   

           experience experienc  
0             <=30000      Good  
1             <=30000      Good  
2    More experienced      Good  
3             <=30000      Good  
4             <=30000      Good  
..                ...       ...  
595           <=30000      Good  
596           <=30000      Good  
597           <=30000      Good  
598           <=30000      Good  
599           <=30000      Good  

[600 rows x 8 columns]

In [9]:
##Droping Work Experience variable
fraud.drop(["Work.Experience"],axis=1,inplace=True)

In [10]:
fraud

Undergrad Marital.Status  City.Population Urban   income  \
0          NO         Single            50047   YES  <=30000   
1         YES       Divorced           134075   YES  <=30000   
2          NO        Married           160205   YES  <=30000   
3         YES         Single           193264   YES  <=30000   
4          NO        Married            27533    NO  <=30000   
..        ...            ...              ...   ...      ...   
595       YES       Divorced            39492   YES  <=30000   
596       YES       Divorced            55369   YES  <=30000   
597        NO       Divorced           154058   YES  <=30000   
598       YES        Married           180083    NO  <=30000   
599        NO       Divorced           158137    NO  <=30000   

           experience experienc  
0             <=30000      Good  
1             <=30000      Good  
2    More experienced      Good  
3             <=30000      Good  
4             <=30000      Good  
..                ...       ...  
595           <=30000      Good  
596           <=30000      Good  
597           <=30000      Good  
598           <=30000      Good  
599           <=30000      Good  

[600 rows x 7 columns]

In [11]:
fraud.rename(columns={"Undergrad":"undergrad","Marital.Status":"marital","Taxable.Income":'income',"City.Population":"population","Urban":"urban"},inplace=True)
## As we are getting error as "ValueError: could not convert string to float: 'YES'".
## Model.fit doesnt not consider String. So, we encode

In [12]:
fraud

undergrad   marital  population urban   income        experience experienc
0          NO    Single       50047   YES  <=30000           <=30000      Good
1         YES  Divorced      134075   YES  <=30000           <=30000      Good
2          NO   Married      160205   YES  <=30000  More experienced      Good
3         YES    Single      193264   YES  <=30000           <=30000      Good
4          NO   Married       27533    NO  <=30000           <=30000      Good
..        ...       ...         ...   ...      ...               ...       ...
595       YES  Divorced       39492   YES  <=30000           <=30000      Good
596       YES  Divorced       55369   YES  <=30000           <=30000      Good
597        NO  Divorced      154058   YES  <=30000           <=30000      Good
598       YES   Married      180083    NO  <=30000           <=30000      Good
599        NO  Divorced      158137    NO  <=30000           <=30000      Good

[600 rows x 7 columns]

In [13]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for column_name in fraud.columns:
    if fraud[column_name].dtype == object:
        fraud[column_name] = le.fit_transform(fraud[column_name])
    else:
        pass

In [14]:
##Splitting data into featuers and labels
features = fraud.iloc[:,0:5]
labels = fraud.iloc[:,5]

In [15]:
features

undergrad  marital  population  urban  income
0            0        2       50047      1       0
1            1        0      134075      1       0
2            0        1      160205      1       0
3            1        2      193264      1       0
4            0        1       27533      0       0
..         ...      ...         ...    ...     ...
595          1        0       39492      1       0
596          1        0       55369      1       0
597          0        0      154058      1       0
598          1        1      180083      0       0
599          0        0      158137      0       0

[600 rows x 5 columns]

In [16]:
labels

0      0
1      0
2      1
3      0
4      0
      ..
595    0
596    0
597    0
598    0
599    0
Name: experience, Length: 600, dtype: int32

In [17]:
## Collecting the column names
colnames = list(fraud.columns)
predictors = colnames[0:5]
target = colnames[5]
##Splitting the data into train and test

In [18]:
colnames

['undergrad',
 'marital',
 'population',
 'urban',
 'income',
 'experience',
 'experienc']

In [19]:
predictors

['undergrad', 'marital', 'population', 'urban', 'income']

In [20]:
target

'experience'

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test = train_test_split(features,labels,test_size = 0.2,stratify = labels)

In [23]:
x_train

undergrad  marital  population  urban  income
342          1        1       31097      1       0
54           0        0       98207      0       0
427          0        0       99025      0       0
3            1        2      193264      1       0
6            0        0       80890      1       0
..         ...      ...         ...    ...     ...
260          1        2       92333      0       0
109          1        1      178585      1       0
238          1        2       72968      1       0
563          1        1      116495      1       0
288          1        1      174196      1       0

[480 rows x 5 columns]

In [24]:
x_test

undergrad  marital  population  urban  income
287          1        2       77102      1       0
128          0        1      100897      1       0
199          1        1      145744      1       0
250          0        1      156973      0       0
442          1        2      193775      0       0
..         ...      ...         ...    ...     ...
575          0        0       95975      1       0
96           0        2       63622      0       0
350          0        1       89949      0       0
332          1        0       84132      0       0
497          0        2      100331      0       0

[120 rows x 5 columns]

In [25]:
y_test

287    0
128    0
199    0
250    0
442    0
      ..
575    0
96     0
350    0
332    0
497    0
Name: experience, Length: 120, dtype: int32

In [26]:
y_train

342    0
54     0
427    0
3      0
6      0
      ..
260    0
109    0
238    0
563    0
288    0
Name: experience, Length: 480, dtype: int32

In [27]:
##Model building
from sklearn.ensemble import RandomForestClassifier as RF

In [28]:
model = RF(n_jobs = 3,n_estimators = 15, oob_score = True, criterion = "entropy")
model.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(


RandomForestClassifier(criterion='entropy', n_estimators=15, n_jobs=3,
                       oob_score=True)

In [29]:
model.estimators_
model.classes_
model.n_features_
model.n_classes_

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:103: FutureWarning: Attribute `n_features_` was deprecated in version 1.0 and will be removed in 1.2. Use `n_features_in_` instead.
  warnings.warn(msg, category=FutureWarning)


2

In [30]:
model.n_outputs_

1

In [31]:
model.oob_score_

0.9416666666666667

In [32]:
##Predictions on train data
prediction = model.predict(x_train)

In [33]:
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [36]:
##Predictions on train data
prediction = model.predict(x_test)

In [37]:
prediction

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
##Predictions on train data
prediction = model.predict(y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [49]:
##Accuracy
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [54]:
y_pred = [0, 2, 1, 3]
y_true = [0, 1, 2, 3]
accuracy_score(y_true, y_pred)

0.5

In [72]:
##Confusion matrix
confusion = confusion_matrix(y_true, y_pred)
confusion

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]], dtype=int64)

In [73]:
##Prediction on test data
pred_test = model.predict(x_test)

In [74]:
pred_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
##Accuracy
acc_test =accuracy_score(y_test,pred_test)
acc_test

0.9416666666666667

In [76]:
%pip install six
%pip install scikit-learn
## In random forest we can plot a Decision tree present in Random forest
import sklearn
from sklearn.tree import export_graphviz
import pydotplus
import six
#sklearn.externals.six = six

#print(sklearn.externals.six)


import six
import sys
sys.modules['sklearn.externals.six'] = six
from sklearn.externals.six import StringIO

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


ModuleNotFoundError: No module named 'pydotplus'

In [77]:
tree = model.estimators_[5]
tree

DecisionTreeClassifier(criterion='entropy', max_features='auto',
                       random_state=582187733)

In [79]:
from io import StringIO as SIO  

In [81]:
dot_data = SIO()
export_graphviz(tree,out_file = dot_data, filled = True,rounded = True, feature_names = predictors ,class_names = target,impurity =False)

In [89]:
pip install pydot

Defaulting to user installation because normal site-packages is not writeable
  Using cached pydot-1.4.2-py2.py3-none-any.whl (21 kB)
Note: you may need to restart the kernel to use updated packages.


In [1]:
graph = pydot.graph_from_dot_data(dot_data.getvalue())

NameError: name 'pydot' is not defined

In [ ]:
## Creating pdf and png file the selected decision tree
%conda install python-graphviz
%conda install pydotplus
graph